lab6/myimgur/app/urls.py
from django.urls import path

from . import views 

app_name='app'
urlpatterns = [
    path('', views.index,name="index"),
    path('<int:image_id>/',views.detail, name="detail"),
    path('<int:image_id>/comment', views.comment, name="comment")
]

lab6/myimgur/myimgur/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('images/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('',views.index, name='root')
]

lab6/myimgur/app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Image(models.Model):
    title = models.CharField(max_length=128, unique=True, blank=False)
    url = models.CharField(max_length=512)
    description = models.TextField(blank=True)
    pub_date=models.DateTimeField('Published at')
    upvotes = models.IntegerField(default=0)
    downvote = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    author = models.CharField(max_length=256, blank=False)


    def __str__(self):
        return f"{self.author}:{self.text[:60]}"

lab6/myimgur/app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect
from .models import Image, Comment
from django.urls import reverse
# Create your views here.

def index(request):
    images = Image.objects.order_by('-pub_date')
    context = { 'images' : images }
    return render(request, 'app/index.html', context)

def detail(request, image_id):
    image=get_object_or_404(Image, pk=image_id)
    comment_list= image.comment_set.all()
    context = { 'image' : image, 'comments':comment_list }
    return render(request, 'app/detail.html', context)

def comment(request, image_id):
    image= get_object_or_404(Image, pk=image_id)
    try:
        comment = image.comment_set.create(author=request.POST['author'], text = request.POST['comment'])
    except Exception as e:
        return render(request, 'app/detail.html'{'image':image,'error_message':str(e)})
    else:
        return HttpResponseRedirect(reverse('app:detail', args=(image.id,)))

lab6/myimgur/app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Lame Imgur</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
        </div>
      </nav>

    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">My Lame Imgur</h1>
              <p class="lead">Your one stop place for posting your lamest images!</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

lab6/myimgur/app/templates/app/detail.html
{% extends 'app/base.html' %}
{% block content %}
    <h1>{{image.title}}</h1>
    <p>{{image.pub_date}}</p>
    <img src="{{ image.url }}" alt="">
    <p>{{image.description}}</p>
    <hr>
    {% if error_message %}
    <p>{{error_message}}</p>
    {%endif%}
    <div>
        {% for comment in comments %}
            <p><strong>{{comment.author}}</strong></p>
            <p>{{comment.text}}</p>
        {%endfor%}
    </div>
    <hr>
    <div>
        <form action="{% url 'app:comment' image.id" method="POST" class="border">
            {%csrf_token%}
            <label for="author">Author</label>
            <input type="text" name="authour", id="author">
            <label for="comment">Comment text</label>
            <textarea name="comment" id="comment" cols="50" rows=4></textarea>
            <input type="submit" value="Comment">
        </form>
    </div>
{% endblock %}

lab6/myimgur/app/templates/app/index.html
{% extends 'app/base.html' %}
{%block content%}
    {% for image in images %}
    <div>
        <h2>
            <a href="{%url 'app:detail' image.id%}">{{image.title}}</a>
        </h2>
    </div>
    {% endfor %}
{% endblock%}